services:
  postgres:
    image: postgres
    container_name: example-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - example-postgres-data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - example-redis-data:/var/lib/redis/data
volumes:
  example-postgres-data:
  example-redis-data: